apiVersion:  v1  
kind: Pod
metadata:  
        name: mypod1
spec:
 containers:
    - name: mypod-cont1
      image: ratnadeepsali/student:latest
      resources: 
          requests:
            cpu: "50m"
            memory: "90Mi"        
      ports:  
        - name: http
          containerPort: 80
          protocol: TCP




